# AUTO-UPDATES
export UPDATE_ZSH_DAYS=1

PATH=/usr/local/bin:/usr/local/sbin:$PATH

# setup perlbrew, npm, cabal
[[ -s "$HOME/perl5/perlbrew/etc/bashrc" ]] && source ~/perl5/perlbrew/etc/bashrc
[[ -d "$HOME/.npm-packages/bin" ]] && PATH=$HOME/.npm-packages/bin:$PATH
[[ -d "$HOME/.cabal/bin" ]] && PATH=$HOME/.cabal/bin:$PATH
[[ -d "$HOME/.cabin/bin" ]] && PATH=$HOME/.cabin/bin:$PATH
[[ -d "$HOME/.nvm" ]] && export NVM_DIR=~/.nvm
[[ -d "$HOME/.nvm" ]] && source $(brew --prefix nvm)/nvm.sh

# RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
# PATH=$HOME/.rvm/bin:$PATH # Add RVM to PATH for scripting

# ENV
if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi
export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'
if [[ -z "$LANG" ]]; then
  export LANG='en_AU.UTF-8'
fi

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi


# Antigen
[[ ! -d ~/.antigen/antigen ]] &&
        mkdir -p ~/.antigen && git clone https://github.com/zsh-users/antigen.git ~/.antigen/antigen

source ~/.antigen/antigen/antigen.zsh

# Load the oh-my-zsh library
antigen use oh-my-zsh

antigen bundles <<EOBUNDLES

  # Helper for extracting different archives
  extract

  git
  git-extras
  gitignore

  emacs

  colored-man

  tmux
  cabal
  httpie
  nvm
  npm
  rvm
  fasd
  #z

  brew
  brew-cask


  # Syntax Highlighting
  zsh-users/zsh-syntax-highlighting
EOBUNDLES

# Load a theme
#antigen theme sindresorhus/pure pure
antigen bundle sindresorhus/pure

# antigen bundle vi-mode

# Tell antigen to execute
antigen apply

#Alias
alias gf='git flow'
alias gcd='git checkout develop'
alias gch='git checkout hotfix'
alias gcr='git checkout release'
alias fuck='eval $(thefuck $(fc -ln -1 | tail -n 1)); fc -R'
