# setting nvm to lazy load
export NVM_LAZY_LOAD=true

# # Uncomment following line if you want red dots to be displayed while waiting for completion
# export COMPLETION_WAITING_DOTS="true"

# # Correct spelling for commands
# setopt correct

# # turn off the infernal correctall for filenames
# unsetopt correctall

# install zplug
if [[ ! -d ~/.zplug ]];then
    git clone https://github.com/b4b4r07/zplug ~/.zplug
fi
source ~/.zplug/init.zsh

alias git=hub

# Async for zsh, used by pure
zplug "mafredri/zsh-async", from:github, defer:0

# allows for lazy loading of nvm
zplug "lukechilds/zsh-nvm", from:github

# reminds you of alias's that are set for commands that you run
zplug "djui/alias-tips", from:github
zplug "chrissicool/zsh-256color", from:github

zplug "lib/completion", from:oh-my-zsh
zplug "lib/key-bindings", from:oh-my-zsh
zplug "lib/history", from:oh-my-zsh
zplug "lib/diretories", from:oh-my-zsh
zplug "lib/termsupport", from:oh-my-zsh

zplug "plugins/git", from:oh-my-zsh
zplug "plugins/git-extras", from:oh-my-zsh
zplug "plugins/tmux", from:oh-my-zsh
zplug "plugins/ssh-agent", from:oh-my-zsh
zplug "plugins/gpg-agent", from:oh-my-zsh
zplug "plugins/cpanm", from:oh-my-zsh
zplug "plugins/colored-man-pages", from:oh-my-zsh
# bunch of command aliases
zplug "plugins/common-aliases", from:oh-my-zsh
zplug "plugins/extract", from:oh-my-zsh
zplug "plugins/mosh", from:oh-my-zsh

if [ $(uname -a | grep -ci Darwin) = 1 ]; then
    # Load OSX-specific plugins
    zplug "plugins/brew", from:oh-my-zsh
    zplug "plugins/osx", from:oh-my-zsh
fi


# Syntax highlighting for commands
zplug "zsh-users/zsh-syntax-highlighting", from:github, defer:2

# Community assembled completions
zplug "zsh-users/zsh-completions", from:github, use:src

# fast/unobtrusive autosuggestions for zsh
zplug "zsh-users/zsh-autosuggestions", from:github

# git aware ls clone
zplug "rimraf/k", from:github

# History substring searching
zplug "zsh-users/zsh-history-substring-search", from:github, defer:3

# Theme!
# zplug "sindresorhus/pure", use:pure.zsh, from:github, as:theme
zplug "intelfx/pure", use:pure.zsh, from:github, as:theme

# Actually install plugins, prompt user input
if ! zplug check --verbose; then
    printf "Install zplug plugins? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

zstyle :omz:plugins:ssh-agent agent-forwarding on

# Set keystrokes for substring searching
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

setopt auto_cd
setopt multios
setopt prompt_subst

alias tsa='tmux new-session -t'
# alias fuck='eval $(thefuck $(fc -ln -1 | tail -n 1)); fc -R'
eval $(thefuck --alias)

# MOSH with SSH fallback.
mosh() {
   if command -v mosh &>/dev/null; then
       command mosh "$@"
       [[ $? -ne 0 ]] && (echo "MOSH failed on remote system. Retrying with SSH." ; command ssh "$@")
   else
       echo "MOSH not found on local system. Retrying with SSH."
       command ssh "$@"
   fi
}

# Yes, these are a pain to customize. Fortunately, Geoff Greer made an online
# tool that makes it easy to customize your color scheme and keep them in sync
# across Linux and OS X/*BSD at http://geoff.greer.fm/lscolors/
export CLICOLOR=1
export LSCOLORS='Exfxcxdxbxegedabagacad'
export LS_COLORS='di=1;34;40:ln=35;40:so=32;40:pi=33;40:ex=31;40:bd=34;46:cd=34;43:su=0;41:sg=0;46:tw=0;42:ow=0;43:'

[[ -n "$WINDOW" ]] && SCREEN_NO="%B$WINDOW%b " || SCREEN_NO=""


[[ -s "$HOME/perl5/perlbrew/etc/bashrc" ]] && source ~/perl5/perlbrew/etc/bashrc
GOPATH=/Users/chris/go
[[ -s "$HOME/go/bin" ]] && PATH=$HOME/go/bin:$PATH
[[ -s "$HOME/.cabal/bin" ]] && PATH=$HOME/.cabal/bin:$PATH
[[ -s "$HOME/.rvm/bin" ]] && PATH="$PATH:$HOME/.rvm/bin"

# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
# End Nix

[[ $(type jenv) ]] && eval "$(jenv init -)"
